//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHelacor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public int Idmarca { get; set; }
        public string nombremarca { get; set; }
    }
}
