//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHelacor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelacorLineadeTortaEntities : DbContext
    {
        public HelacorLineadeTortaEntities()
            : base("name=HelacorLineadeTortaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Produccion> Produccion { get; set; }
        public virtual DbSet<Produccion_Marca> Produccion_Marca { get; set; }
        public virtual DbSet<Produccion_Marca_Pais> Produccion_Marca_Pais { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
    }
}
