//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHelacor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion_Marca_Pais
    {
        public int Id_Produccion_Marca_Pais { get; set; }
        public int Idproduccion_marca { get; set; }
        public int Idpais { get; set; }
        public Nullable<System.DateTime> Fecha_Operacion { get; set; }
        public string Descripcion_Operacion { get; set; }
    }
}
