//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHelacor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Idproducto { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Unidad { get; set; }
        public string Peso_Helado { get; set; }
        public string Peso_Total { get; set; }
        public Nullable<System.DateTime> Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Operacion { get; set; }
        public Nullable<decimal> Producto_Baja { get; set; }
        public string Operacion { get; set; }
        public string Descripcion_Operacion { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    }
}
