//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHelacor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int Idturno { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Horario_Inicio { get; set; }
        public Nullable<System.DateTime> Horario_Fin { get; set; }
    }
}
